# Generated by Django 5.2.6 on 2025-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Sharing', 'Sharing'), ('Other', 'Other')], max_length=50),
        ),
    ]
